name: Build

on:
  schedule:
    - cron: "1 1 * * 1"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      upstream_ver: ${{ steps.upstream-ver.outputs.upstream_ver }}
      repo_ver: ${{ steps.repo-ver.outputs.repo_ver }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check latest tag
        id: repo-ver
        run: |
          git tag --sort=committerdate | tail -1
          repo_ver="$(git tag --sort=committerdate | tail -1)"
          echo "${repo_ver}"
          echo "repo_ver=${repo_ver}" >> "$GITHUB_OUTPUT"
      - name: Clone repo
        run: |
          git clone 'https://aur.archlinux.org/aws-cli-v2.git'
      - name: Check upstream version
        id: upstream-ver
        working-directory: ./aws-cli-v2
        run: |
          pkgver=$(grep -oP "^pkgver='?\K[\d\.]+" './PKGBUILD')
          pkgrel="$(grep -oP "^pkgrel=\K\d+" './PKGBUILD')"
          echo "upstream_ver=${pkgver}-${pkgrel}" >> "$GITHUB_OUTPUT"
  build_and_release:
    if: needs.test.outputs.upstream_ver != needs.test.outputs.repo_ver
    needs: test
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install git & gnupg
        run: |
          pacman -Syu --noconfirm git gnupg
      - name: Import keyring
        # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html#install-linux-instructions
        run: |
          gpg --import "A6310ACC4672.pub"
      - name: Clone repo
        run: |
          git clone 'https://aur.archlinux.org/aws-cli-v2.git'
      - name: Build
        working-directory: ./aws-cli-v2
        # Enable root to run makepkg
        run: |
          sed -i '/E_ROOT/d' /usr/bin/makepkg
          sed -i 's/ debug / !debug /g' /etc/makepkg.conf
          makepkg -s --noconfirm
      - name: Sanitise filename
        working-directory: ./aws-cli-v2
        run: |
          for i in $(find "." -type f -name "*.zst" | grep -E '[":<>|*?]+' || true); do
            echo "'$i' filename contains invalid character, renaming..."
            # "!" is used as a sed separator
            mv "$i" $(echo "$i" | sed -E 's![":<>|*?]+!_!g')
          done;
      - name: Generate hashsums
        working-directory: ./aws-cli-v2
        run: |
          sha256sum *.zst > SHA256SUMS
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./aws-cli-v2/*.zst
          retention-days: 30
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{needs.test.outputs.upstream_ver}}
          body: ${{needs.test.outputs.upstream_ver}}
          commit: main
          makeLatest: true
          artifacts: "./aws-cli-v2/*.zst,./aws-cli-v2/SHA256SUMS"
